services:
  db_drivenops:
    image: postgres
    container_name: db_drivenops
    restart: always
    ports:
      - 6022:5432
    env_file:
      - back-end/.env
    volumes:
      - db_drivenops:/var/lib/postgresql/data

  server_drivenops:
    container_name: server_drivenops
    build: ./back-end
    image: node_sorteador_app_image
    ports:
      - 5000:5000
    depends_on:
      - db_drivenops
    env_file:
      - back-end/.env

  react_sorteador_app:
    container_name: react_sorteador_app
    build: ./front-end
    image: react_sorteador_app_image
    volumes:
     - build_react:/var/www/html

  nginx_sorteador_app:
    container_name: nginx_sorteador_app
    build: ./nginx
    image: nginx_sorteador_app_image
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db_drivenops
      - server_drivenops
      - react_sorteador_app
volumes:
  db_drivenops:
  build_react: