services:
  db_drivenops:
    image: postgres
    container_name: db_drivenops
    restart: always
    ports:
      - 6022:5432
    env_file:
      - .env.test

  server_drivenops:
    container_name: server_drivenops
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_drivenops
    env_file:
      - .env.test