version: "3"
services:
  db_drivenops:
    image: postgres
    container_name: db_drivenops
    restart: always
    ports:
      - 6022:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data

  server_drivenops:
    container_name: server_drivenops
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_drivenops
    env_file:
      - .env
volumes:
  pg: